#!/bin/sh
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

# Create folders
sudo rm -rf $root/pi-server/client
mkdir $root/pi-server/client
sudo chmod -R 777 $root/pi-server/client
mkdir $root/pi-server/client/build
sudo chmod -R 777 $root/pi-server/client/build

# Install Node JS
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g npm

# Create React App
cd $root/pi-server
npx create-react-app client

# Generate Build
cd $root/pi-server/client
npm run build