#!/bin/bash
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

# Install
cd $root
sudo rm -rf sherlock
git clone https://github.com/sherlock-project/sherlock.git
cd sherlock

# Create virtual environment
apt-get install python3-venv -y
python3 -m venv .venv
.venv/bin/pip3 install -r requirements.txt

# Create alias
al="alias sherlock='sudo $root/sherlock/.venv/bin/python3 sherlock'"

cd $rpias
source core
REPLACE_LINE "$root/.bashrc" "$al"
echo $al >> $root/.bashrc
source $root/.bashrc