#!/usr/bin/env bash

# Install
cd /home/pi
sudo rm -rf sherlock
git clone https://github.com/sherlock-project/sherlock.git
cd sherlock

# Create virtual environment
apt-get install python3-venv -y
python3 -m venv .venv
.venv/bin/pip3 install -r requirements.txt

# Create alias
al="alias sherlock='sudo /home/pi/sherlock/.venv/bin/python3 sherlock'"

REPLACE_LINE "/home/pi/.bashrc" "$al"
echo $al >> /home/pi/.bashrc
source /home/pi/.bashrc