#!/bin/bash
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

# Create folders
sudo rm -rf $root/pi-server
mkdir $root/pi-server
sudo chmod -R 777 $root/pi-server

# Install Node JS
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g npm

# Install Server
cat $dir/_server.txt >> $root/pi-server/server.js
cd $root/pi-server
npm init -y
npm i express

# Setup boot script
file=/etc/rc.local
search="exit 0"

a="cd $root/pi-server && npm start &"
b="cd $root/pi-server && .venv/bin/flask --app server.py run --no-debugger --host=0.0.0.0 -p 5001 &"

# Remove exit 0
sudo ex -s +"g/$search/d" -cwq $file

# Replace existent
cd $rpias
source core
REPLACE_LINE "$file" "$a"
REPLACE_LINE "$file" "$b"

# Append lines
sudo echo $a >> $file
sudo echo $search >> $file