#!/bin/bash

reset='\033[0m'           # Reset
red='\033[0;31m'          # Red
green='\033[0;32m'        # Green
yellow='\033[0;33m'       # Yellow
purple='\033[0;35m'       # Purple

if [ $# = 0 ]; then
    echo
    echo "${yellow}You must specify the options to execute.${reset}"
    echo
    echo "Example: ${purple}rpia${reset} --autologin=on --splash=off --nextjs --chrome --smb --reboot"
    echo
    echo
    exit 0
fi

clear
echo
echo "[${purple}Started${reset}] RPI Auto-Setup"


reboot=false
destroy=false
success=""
skipped=""
failed=""

# Root folder
root=~
# Setup folder
rpias=$root/rpia
# Modules folder
mods=$rpias/modules
# Load functions
source $rpias/core

# Disable Reboot
if [ -f "/sbin/reboot" ]; then
    sudo mv /sbin/reboot /sbin/reboot.disabled
fi

# Iterate arguments
for arg in "$@"; do

    key="${arg%%=*}"
    value="${arg#*=}"
    strip="${key#--}"

    # Check if arg starts with --
    if [ "$strip" != "$arg" ]; then

        if [ -f "$mods/$strip/install" ]; then
            echo 
            echo "[${green}Executing${reset}] $strip $value"
            echo 
            sh "$mods/$strip/install" $root $rpias $value
            success="$success $arg"

        elif [ -f "$mods/$strip-$value/install" ]; then
            echo 
            echo "[${green}Executing${reset}] $strip $value"
            echo 
            sh "$mods/$strip-$value/install" $root $rpias $value
            success="$success $arg"

        else
            if [ "$key" = "--reboot" ]; then
                reboot=true
                continue
            fi
            if [ "$key" = "--destroy" ]; then
                destroy=true
                continue
            fi

            echo 
            echo "[${red}Failed${reset}] Invalid arg: $arg"
            skipped="$skipped $arg"
        fi

    else
        echo 
        echo "[${red}Failed${reset}] Invalid arg: $arg"
        echo 
        skipped="$skipped $arg"
    fi

done

# Print Success
echo
echo "[${green}Completed${reset}] rpia $(printf '%s ' "$success")"
echo

# Print Skipped
if [ "$skipped" != "" ]; then
    echo "[${yellow}Skipped${reset}]: $(printf '%s ' "$skipped")"
    echo
fi

# Print Failed
if [ "$failed" != "" ]; then
    echo "[${red}Failed${reset}]: $(printf '%s ' "$failed")"
    echo
fi

# Enable Reboot
if [ -f "/sbin/reboot.disabled" ]; then
    sudo mv /sbin/reboot.disabled /sbin/reboot
fi

# Destroy files
if [ $destroy = true ]; then
    sudo rm -rf $rpias
    sudo rm -rf /usr/local/bin/rpia
fi

# Reboot device
if [ $reboot = true ]; then
    sudo reboot
fi