#!/bin/sh

REPLACE_LINE() {
    file_content=$(<$1)
    file_content=${file_content//$2/$3}
    echo "$file_content" > $1
}

REMOVE_LINE() {
    sudo ex -s +"g/$2/d" -cwq $1
}

RESTORE() {
    if [ -f "$1.orig" ]; then
        sudo cp $1.orig $1
    elif [ -f "$1" ]; then
        sudo cp $1 $1.orig
    fi
}

# TOGGLE_SERVICE() {
#     if [ -f "/etc/systemd/system/$1.service" ]; then
#         sudo systemctl stop $1
#         sudo systemctl disable $1
#         sudo rm -f /etc/systemd/system/$1.service
#     else
#         CREATE_SERVICE "$1" "$2"
#     fi
# }

# CREATE_SERVICE() {
#     service=/etc/systemd/system/$1.service
#     sudo rm -f $service
#     sudo touch $service
#     sudo echo "[Unit]" > $service
#     sudo echo "Description=$1" >> $service
#     sudo echo "Before=network.target" >> $service
#     sudo echo "" >> $service
#     sudo echo "[Service]" >> $service
#     sudo echo "ExecStart=/bin/bash -c '$2'" >> $service
#     sudo echo "StandardOutput=inherit" >> $service
#     sudo echo "StandardError=inherit" >> $service
#     sudo echo "Restart=always" >> $service
#     sudo echo "User=pi" >> $service
#     sudo echo "Group=pi" >> $service
#     sudo echo "WorkingDirectory=/home/pi/$1" >> $service
#     sudo echo "" >> $service
#     sudo echo "[Install]" >> $service
#     sudo echo "WantedBy=multi-user.target" >> $service
#     sudo systemctl enable $1
#     sudo systemctl start $1
# }
