#!/bin/sh

REPLACE_LINE() {
    file_content=$(<$1)
    file_content=${file_content//$2/$3}
    echo "$file_content" > $1
}

REMOVE_LINE() {
    sudo ex -s +"g/$2/d" -cwq $1
}

RESTORE() {
    if [ -f "$1.orig" ]; then
        sudo cp $1.orig $1
    elif [ -f "$1" ]; then
        sudo cp $1 $1.orig
    fi
}