#!/bin/sh

REPLACE_LINE() {
    file_content=$(<$1)
    file_content=${file_content//$2/$3}
    echo "$file_content" > $1
}

WRITE_CONFIG() {
    while read line; do
        sudo ex -s +"g/$line/d" -cwq $2
    done <$1
    sudo cat $1 >> $2
}