#!/bin/bash
root=$1
rpias=$2
value=$3
dir=$(dirname $0)
config=/boot/config.txt

source $rpias/core

if [ "$value" = "on" ]; then
    REPLACE_LINE "$config" "enable_uart=0"
    REPLACE_LINE "$config" "disable_splash=1"
    REPLACE_LINE "$config" "avoid_warnings=2"

    echo "enable_uart=1" >> $config
    echo "disable_splash=0" >> $config

elif [ "$value" = "off" ]; then
    REPLACE_LINE "$config" "enable_uart=1"
    REPLACE_LINE "$config" "disable_splash=0"

    echo "enable_uart=0" >> $config
    echo "disable_splash=1" >> $config
    echo "avoid_warnings=2" >> $config
else
    exit 0
fi

echo "Config changed at: $config"
echo "Please reboot your device for changes to take effect."
