#!/bin/sh
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

cd $root
git clone https://github.com/LionSec/katoolin.git
sudo cp katoolin/katoolin.py /usr/bin/katoolin
sudo chmod +x /usr/bin/katoolin
sudo katoolin