#!/usr/bin/env bash
# Toggle console auto-login for Raspberry Pi (Debian-based)
# Works with systemd on Raspberry Pi OS, Ubuntu, etc.

VALUE=${1:-on}
USER=$(who -m | awk '{ print $1 }')

SERVICE="getty@tty1"
SERVICE_DIR="/etc/systemd/system/${SERVICE}.service.d"
SERVICE_FILE="${SERVICE_DIR}/autologin.conf"

if [ -d "$SERVICE_DIR" ]; then
    sudo rm -rf $SERVICE_DIR
fi

if [ "$VALUE" = "on" ]; then
    echo "Enabled auto-login for user '${USER}'..."

    sudo mkdir -p $SERVICE_DIR

    sudo cat > $SERVICE_FILE << EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin $USER --noclear %I \$TERM
EOF

    sudo systemctl enable $SERVICE
else
    echo "Disabled auto-login for user '${USER}'..."
    sudo systemctl disable $SERVICE
fi

sudo systemctl daemon-reexec
sudo systemctl daemon-reload

echo "Please reboot your device for changes to take effect."
