#!/bin/bash
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

ssid="Wifi Guest"
config=/etc/dhcpcd.conf
apconfig=/etc/hostapd/hostapd.conf
apdaemon=/etc/default/hostapd
dnsconfig=/etc/dnsmasq.conf
masqconfig=/etc/sysctl.conf

source $rpias/core

# Setup dhcpcd
RESTORE "$config"
sudo cat > $config << EOF
interface wlan0
static ip_address=192.168.4.1/24
nohook wpa_supplicant
EOF
sudo service dhcpcd restart

# Setup dnsmasq
RESTORE "$dnsconfig"
sudo cat > $dnsconfig << EOF
interface=wlan0
dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h
EOF
sudo systemctl start dnsmasq

if [ "$value" != "--wifi" ]; then
    ssid=$value
fi

# Setup access point
RESTORE "$apconfig"
sudo cat > $apconfig << EOF
country_code=EN
interface=wlan0
ssid=$ssid
channel=9
auth_algs=1
EOF

# Setup daemon
RESTORE "$apdaemon"
echo DAEMON_CONF="/etc/hostapd/hostapd.conf" >> $apdaemon

# Start access point
sudo systemctl unmask hostapd
sudo systemctl enable hostapd
sudo systemctl start hostapd

# Setup IP Masquerading
RESTORE "$masqconfig"
echo "net.ipv4.ip_forward=1" >> $masqconfig
sudo iptables -t nat -A  POSTROUTING -o eth0 -j MASQUERADE
sudo iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
sudo netfilter-persistent save
