#!/bin/sh
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

# Setup boot script
file=/etc/rc.local
search="exit 0"

# REST - Node
a="cd $root/pi-server && npm start &"

# REST - Python
b="cd $root/pi-server && .venv/bin/flask --app server.py run --no-debugger --host=0.0.0.0 -p 5001 &"

# Find strings
aE=$(cat $file | grep "$a")
bE=$(cat $file | grep "$b")

# Install LCD-SHOW
cd $root
sudo rm -rf LCD-show
git clone https://github.com/goodtft/LCD-show.git
chmod -R 755 LCD-show
cd LCD-show/
sudo ./$value-show
sudo mv /usr/share/X11/xorg.conf.d/99-fbturbo.conf ~

# Remove if exist
if [ "$aE" != "" ]; then

    # Remove exit 0
    sudo ex -s +"g/$search/d" -cwq $file

    # Append lines
    sudo echo $a >> $file
    sudo echo $b >> $file
    sudo echo $search >> $file

elif [ "$bE" != "" ]; then

    # Remove exit 0
    sudo ex -s +"g/$search/d" -cwq $file

    # Append lines
    sudo echo $c >> $file
    sudo echo $d >> $file
    sudo echo $search >> $file

fi
