#!/bin/bash
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

config=/etc/samba/smb.conf
folder=shared

sudo rm -rf $root/$folder
mkdir $root/$folder
sudo chmod -R 777 $root/$folder
sudo apt install -y samba samba-common-bin

if [ "$value" != "--smb" ]; then
    folder=$value
fi

source $rpias/core

RESTORE "$config"
sudo cat > $config << EOF
[$folder]
path=$root/$folder
public = yes
read only = no
guest only = yes
writeable = yes
browseable = yes
guest ok = yes
force create mode = 0666
force directory mode = 0777
EOF