#!/bin/sh
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

config=/etc/samba/smb.conf
folder=shared

sudo rm -rf $root/$folder
mkdir $root/$folder
sudo chmod -R 777 $root/$folder
sudo apt install -y samba samba-common-bin

if [ "$value" != "--smb" ]; then
    folder=$value
fi

source $rpias/core

RESTORE "$config"
sudo echo "[$folder]" >> $config
sudo echo "path=$root/$folder" >> $config
sudo echo "public = yes" >> $config
sudo echo "read only = no" >> $config
sudo echo "guest only = yes" >> $config
sudo echo "writeable = yes" >> $config
sudo echo "browseable = yes" >> $config
sudo echo "guest ok = yes" >> $config
sudo echo "force create mode = 0666" >> $config
sudo echo "force directory mode = 0777" >> $config