#!/bin/bash
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

sudo rm -rf $root/shared
mkdir $root/shared
sudo chmod -R 777 $root/shared
sudo apt install -y samba samba-common-bin
sudo cat $dir/_smb.txt >> /etc/samba/smb.conf