#!/bin/sh
export HOME=/home/pi
# Install Node JS
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs
npm install -g -y create-next-app

# Remove folders
sudo rm -rf $HOME/nextjs

# Create Next JS App
cd $HOME
npm create-next-app@latest nextjs \ 
  --tailwind \
  --react-compiler \
  --no-linter \
  --ts \
  --src-dir \
  --use-npm \
  --no-app \
  --no-turbopack \
  --skip-install \
  --disable-git \
  --import-alias "@/*"

# Add to rc.local
file=/etc/rc.local
search="fbcp &"
command="cd /home/pi/nextjs && npm start &\n\n$search"
found=$(cat $file | grep "$command")

if [ "$found" != "" ]; then
    REPLACE_LINE "$file" "$command"
    REPLACE_LINE "$file" "$search" "$command"
else
    REPLACE_LINE "$file" "$search" "$command"
fi
