#!/bin/bash
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

cd /home/pi

# Remove folders
sudo rm -rf nextjs

# Install Node JS
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g npm

# Create Next JS App
npx --yes create-next-app@latest nextjs --tailwind --react-compiler --no-linter --ts --src-dir --use-npm --no-app --no-turbopack --import-alias "@/*"

search="fbcp &"
source $rpias/core
REPLACE_LINE /etc/rc.local "$search" "cd /home/pi/nextjs && npm start &\n\n$search"