#!/bin/sh
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

sudo apt-get install --no-install-recommends xserver-xorg x11-xserver-utils xinit openbox chromium-browser -y
sudo mv /usr/share/X11/xorg.conf.d/99-fbturbo.conf ~
sudo cat $dir/_bash.txt > $root/.bash_profile
sudo cat $dir/_xinit.txt > $root/.xinitrc