#!/bin/sh
root=$1
rpias=$2
value=$3

cd $rpias
sudo apt-get install --no-install-recommends xserver-xorg x11-xserver-utils xinit openbox chromium-browser -y
sudo cat _bash.txt > $root/.bash_profile
sudo cat _xinit.txt > $root/.xinitrc