#!/bin/sh
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

# Create folders
sudo rm -rf $root/pi-server
mkdir $root/pi-server
sudo chmod -R 777 $root/pi-server

# Install Server
cat $dir/_server.txt >> $root/pi-server/server.py
cd $root/pi-server

# Create virtual environment
apt-get install python3-venv -y
python3 -m venv .venv

# Install requirements
.venv/bin/pip3 install flask
.venv/bin/pip3 install python-dotenv

# Setup boot script
file=/etc/rc.local
search="exit 0"
a="cd $root/pi-server"
b=".venv/bin/flask --app server.py run --no-debugger -p 5001 &"

# Remove exit 0
sudo ex -s +"g/$search/d" -cwq $file

aE=$(cat $file | grep "$a")
bE=$(cat $file | grep "$b")

# Remove if exist
if [ "$aE" != "" ] && [ "$bE" != "" ]; then
    sudo ex -s +"g/$a/d" -cwq $file
    sudo ex -s +"g/$b/d" -cwq $file
fi

# Append lines
sudo echo $a >> $file
sudo echo $b >> $file
sudo echo $search >> $file