#!/bin/sh
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

# Create folders
sudo rm -rf $root/pi-server
mkdir $root/pi-server
sudo chmod -R 777 $root/pi-server

# Install Server
cat $dir/_server.txt >> $root/pi-server/server.py
cd $root/pi-server

# Create virtual environment
apt-get install python3-venv -y
python3 -m venv .venv

# Install requirements
.venv/bin/pip3 install flask
.venv/bin/pip3 install python-dotenv

# Setup boot script
file=/etc/rc.local
search="exit 0"

a="cd $root/pi-server && npm start &"
b="cd $root/pi-server && .venv/bin/flask --app server.py run --no-debugger --host=0.0.0.0 -p 5001 &"

# Remove exit 0
sudo ex -s +"g/$search/d" -cwq $file

# Replace existent
source core
REPLACE_LINE "$file" "$a"
REPLACE_LINE "$file" "$b"

# Append lines
sudo echo $b >> $file
sudo echo $search >> $file