#!/bin/sh
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

# Create folders
sudo rm -rf $root/pi-server
mkdir $root/pi-server

# Install Server
cat $dir/_server.txt >> $root/pi-server/server.py
cd $root/pi-server

# Create virtual environment
python3 -m venv venv

# Activate virtual environment
source venv/bin/activate

# Install requirements
pip install flask
pip install python-dotenv

# Deactivate virtual environment
source deactivate

# Setup boot script
file=/etc/rc.local
search="exit 0"
a="cd $root/pi-server"
b="$root/pi-server/venv/bin/flask --app $root/pi-server/server.py run --no-debugger &"

# Remove exit 0
sudo ex -s +"g/$search/d" -cwq $file

aE=$(grep -Fxq "$a" $file)
bE=$(grep -Fxq "$b" $file)

# Remove if exist
if $aE && $bE; then
    sudo ex -s +"g/$a/d" -cwq $file
    sudo ex -s +"g/$b/d" -cwq $file
fi

# Append lines
sudo echo $a >> $file
sudo echo $b >> $file
sudo echo $search >> $file