#!/bin/sh
root=$1
rpias=$2
value=$3

# Create folders
sudo rm -rf $root/pi-server
mkdir $root/pi-server

# Install Node JS
cd $rpias
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g npm

# Install Server
cat _node.txt >> $root/pi-server/server.js
cd $root/pi-server
npm init -y
npm i express

# Setup boot script
file=/etc/rc.local
search="exit 0"
a="cd $root/pi-server"
b="npm start"

# Remove exit 0
sudo ex -s +"g/$search/d" -cwq $file

aE=$(grep -Fxq "$a" $file)
bE=$(grep -Fxq "$b" $file)

# Remove if exist
if $aE && $bE; then
    sudo ex -s +"g/$a/d" -cwq $file
    sudo ex -s +"g/$b/d" -cwq $file
fi

# Cut last line
sudo sed -i '$d' $file

# Append lines
sudo echo $a >> $file
sudo echo $b >> $file
sudo echo $search >> $file