#!/bin/sh
root=$1
rpias=$2
value=$3
dir=$(dirname $0)

# Create folders
sudo rm -rf $root/pi-server

sudo cp -R $dir/pi-server $root
sudo chmod -R 777 $root/pi-server

cd $root/pi-server
npm init -y
npm i express

# Setup boot script
file=/etc/rc.local
search="exit 0"

a="cd $root/pi-server && npm start &"
b="cd $root/pi-server && .venv/bin/flask --app server.py run --no-debugger --host=0.0.0.0 -p 5001 &"

# Remove exit 0
sudo ex -s +"g/$search/d" -cwq $file

# Replace existent
cd $rpias
source core
REPLACE_LINE "$file" "$a"
REPLACE_LINE "$file" "$b"

# Append lines
sudo echo $a >> $file
sudo echo $search >> $file

echo "Files copied to $root/pi-server"
